[phases.setup]
aptPkgs = ["python3", "gcc"]

[phases.build]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[phases.start]
cmds = ["python manage.py runserver 0.0.0.0:8000"]