"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# BASE_DIR 정의 위에 위치
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "0") == "1"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS").split(",")
# CSRF_TRUSTED_ORIGINS= os.environ.get("CSRF_TRUSTED_ORIGINS").split(",")
# CSRF_COOKIE_SECURE = False
# SESSION_COOKIE_SECURE = False
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# customize
AUTH_USER_MODEL = 'account.CustomUser'

# 로그인 지속 시간
# SESSION_COOKIE_AGE = 3600
# SESSION_COOKIE_SAMESITE = "Lax"
# SESSION_COOKIE_SECURE = False
# SESSION_COOKIE_HTTPONLY=True

# Application definition
INSTALLED_APPS = [
    "django.contrib.staticfiles",
    'jazzmin',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'account',
    'finance',
    'cost.cost_base',
    'cost.report',
    'main',
    'umass',
    'securityreinvent.sr_base',
    'securityreinvent.visitor',
    'securityreinvent.parking',
    'securityreinvent.truck',
    'securityreinvent.delivery',
    'securityreinvent.reinvent',
    'quality.flasktodo',
    'whitenoise.runserver_nostatic',
]
JAZZMIN_SETTINGS = {
    "site_title": "Database",        # 브라우저 탭 제목
    "site_header": "Database",       # 상단 로고 제목
    "site_brand": "Database Management",     # 왼쪽 상단 로고/텍스트
    "welcome_sign": "Welcome to Database Management System",
    "copyright": "CheilPengtai",
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'backend.middleware.csrf_exempt_paths.CsrfExemptFinanceApiMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "backend.middleware.thread_local.ThreadLocalMiddleware",
]

# settings.py
WHITENOISE_AUTOREFRESH = DEBUG  # 개발 중 변경 즉시 반영

CORS_ALLOW_CREDENTIALS = True  # ✅ 세션/쿠키 인증 시 필수

ROOT_URLCONF = 'backend.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "build",],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',  # 프로젝트 내부에 저장됨
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 1},
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


LANGUAGE_CODE = 'en-us'   # ✅ 한국어(대한민국)로 변경
TIME_ZONE = 'Asia/Seoul'  # ✅ 한국 시간
USE_TZ = False             # (UTC저장 + KST변환 방식)

DEBUG = True
# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# Location where static files will be collected
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# For debugging purposes, during development (optional):
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # 추가적인 static 폴더가 있다면 설정
    os.path.join(BASE_DIR, 'quality/flasktodo/static'),
    os.path.join(BASE_DIR, 'build/static'),
]

# White noise static stuff
STATIC_ROOT=BASE_DIR / 'staticfiles'
if DEBUG:
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
else:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# https://docs.djangoproject.com/en/5.2/howto/static-files/
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 로그인 
LOGIN_URL = '/account/login/'           # 로그인 페이지


# 로그 폴더 보장
LOG_DIR = BASE_DIR.parent / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[%(asctime)s] %(levelname)s %(name)s:%(lineno)d | user=%(user)s | %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "filters": {
        "user_filter": {
            "()": "backend.middleware.logging_filters.UserFilter",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "INFO",                  # ✅ INFO 이상
            "formatter": "verbose",
            "filters": ["user_filter"],
        },
        "file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "level": "INFO",                  # ✅ INFO 이상
            "when": "midnight",
            "backupCount": 7,
            "filename": os.path.join(LOG_DIR, "app.log"),  # ✅ 절대경로 권장
            "formatter": "verbose",
            "encoding": "utf-8",
            "filters": ["user_filter"],
        },
    },
    "loggers": {
        # Django 자체 로그
        "django": {"handlers": ["console", "file"], "level": "INFO", "propagate": True},
        # 앱 로그: finance.* 로거가 여기로 올라옵니다
        "finance": {"handlers": ["console", "file"], "level": "INFO", "propagate": False},
        # 루트 로거(원하면 켜두세요)
        "": {"handlers": ["console"], "level": "WARNING"},
    },
}
