# Generated by Django 5.2.7 on 2025-11-01 15:46

import django.db.models.deletion
import securityreinvent.truck.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=255, null=True)),
                ('license_plate', models.CharField(max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('truck_number', models.CharField(max_length=255, null=True)),
                ('direct_cntr', models.CharField(max_length=255, null=True)),
                ('in_trailer', models.CharField(max_length=255, null=True)),
                ('seal_number', models.CharField(max_length=255, null=True)),
                ('checkin_at', models.DateTimeField(blank=True, null=True)),
                ('checkout_at', models.DateTimeField(blank=True, null=True)),
                ('out_trailer', models.CharField(blank=True, max_length=255, null=True)),
                ('load_status', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to=securityreinvent.truck.models.upload_location)),
                ('checkin_pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_pic', to=settings.AUTH_USER_MODEL)),
                ('checkout_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_pic', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Truck Tracking Data',
            },
        ),
    ]
