# Generated by Django 5.2.5 on 2025-09-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapprocessed',
            name='project_category',
            field=models.CharField(choices=[('General', 'General'), ('Sharing', 'Sharing'), ('Will', 'Will'), ('NoCode', 'NoCode')], default='General', max_length=20),
        ),
        migrations.AlterField(
            model_name='teamprediction',
            name='project_category',
            field=models.CharField(choices=[('General', 'General'), ('Sharing', 'Sharing'), ('Will', 'Will'), ('NoCode', 'NoCode')], default='General', max_length=20),
        ),
    ]
