# Generated by Django 5.2.6 on 2025-09-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_sapprocessed_project_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprediction',
            name='shared_dominate',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
