# Generated by Django 5.2.6 on 2025-09-07 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_teamprediction_shared_dominate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprediction',
            name='dominant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='finance.teamprediction'),
        ),
    ]
