# Generated by Django 5.2.7 on 2025-11-01 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOfMonthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('register_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('register_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViolatorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_plate', models.CharField(max_length=255)),
                ('parking_lot', models.CharField(max_length=255)),
                ('parking_at', models.DateTimeField(auto_now_add=True)),
                ('violate_count', models.IntegerField()),
                ('register_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
