# ✅ SAP 업로드용 컬럼 매핑
SAP_COL_MAP = {
    "Item": "item",
    "Version": "version",
    "CoCd": "cocd",
    "Consoli.Company(T)": "consoli_company_t",
    "BusA": "busa",
    "Description": "description",
    "Period": "period",
    "Tr.prt": "tr_prt",
    "Trading Partner(T)": "trading_partner_t",
    "Representative Custo": "representative_custo",
    "Representative Custo(T)": "representative_custo_t",
    "Domestic/Overseas(T)": "domestic_overseas_t",
    "Exsiting/New(T)": "exsiting_new_t",
    "Compensation Type": "compensation_type",
    "Compensation Type(T)": "compensation_type_t",
    "HQ/LOCAL(T)": "hq_local_t",
    "RHQ(T)": "rhq_t",
    "Customer": "customer",
    "Custmer(T)": "custmer_t",
    "Product": "product",
    "Product number(T)": "product_number_t",
    "SOff.": "soff",
    "Sales Office(T)": "sales_office_t",
    "Ship-To": "ship_to",
    "Ship-to party(T)": "ship_to_party_t",
    "Bill To": "bill_to",
    "Bill-to party(T)": "bill_to_party_t",
    "Trading Type": "trading_type",
    "Customer group 2": "customer_group_2",
    "Matl Group": "matl_group",
    "D/I Category": "di_category",
    "D/I Category(T)": "di_category_t",
    "Appropriate project": "appropriate_project",
    "WBS Element": "wbs_element",
    "Project(T)": "project_t",
    "PH01-2": "ph01_2",
    "ProdHier01-2(T)": "prodhier01_2_t",
    "Billing Amt (HQ)": "billing_amt_hq",
    "T-Sales": "t_sales",
    "T-COGS": "t_cogs",
    "T-Revenue": "t_revenue",
    "T-Labor Cost": "t_labor_cost",
    "T-Expense": "t_expense",
    "T-Non Operating": "t_non_operating",
    "T-Net Income before Tax": "t_net_income_before_tax",
}

# ✅ CCTR 업로드용 컬럼 매핑
CCTR_COL_MAP = {
    "Company": "company",
    "BA": "ba",
    "Cost Center": "cost_center",
    "Name(20字)": "name_20",
    "Name(40字)": "name_40",
    "유형": "type_t",
    "배부기준": "allocation_standard",
    "Cost Center Category": "cost_center_category",
    "Sales Office Cd": "sales_office_cd",
}

# ✅ Gate 업로드용 컬럼 매핑
GATE_COL_MAP = {
    "Job": "job",
    "보상유형": "compensation_type",
    "Job name": "job_name",
    "Project": "project",
    "Job type Group": "job_type_group",
    "Job type": "job_type",
    "광고팀": "ad_team",
    "광고주ID": "advertiser_id",
    "광고주명": "advertiser_name",
    "상태": "status",
    "Job category": "job_category",
    "보상유형.1": "compensation_type_1",
    "기존/개발": "existing_new",
    "제작형태": "production_type",
    "광고주측 담당자": "advertiser_manager",
    "제품/브랜드": "product_brand",
    "계약유형": "contract_type",
    "기간(시작)": "period_start",
    "기간(예상종료)": "period_end",
    "광고주 OT일": "advertiser_ot_date",
    "광고팀담당자": "ad_team_manager",
    "제작팀": "production_team",
    "제작팀장(CD)": "production_team_cd",
    "코드 승인관리자": "code_approver",
    "정산팀": "settlement_team",
    "가상정산부서": "virtual_settlement_dept",
    "정산담당자": "settlement_manager",
    "PM 담당팀": "pm_team",
    "PM담당자": "pm_manager",
    "청구": "billing",
    "Plan시간": "plan_time",
    "계약시간": "contract_time",
    "스탭인원수": "staff_count",
    "생성일자": "created_date",
    "생성자": "created_by",
    "메인스탭(AE)": "main_staff_ae",
    "Active 수행자": "active_executor",
    "Active일자": "active_date",
    "Job 마감일자": "job_deadline",
    "계약 Job": "contract_job",
    "참조 Project": "ref_project",
    "Log Project Key": "log_project_key",
    "RFP/Q No.": "rfp_q_no",
    "BML 타입": "bml_type",
    "법무포탈 계약서번호": "legal_contract_no",
    "연결자": "connector",
    "연결일자": "connection_date",
    "청구처(거점간거래)": "billing_spot_trade",
    "상세설명": "description",
    "RA Key": "ra_key",
    "BA Code": "ba_code",
    "Business Area": "business_area",
}
